package assets.beardmobs.entities.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelVesperQueen extends ModelBase
{
  //fields
    ModelRenderer Body_base;
    ModelRenderer Body_mid;
    ModelRenderer Body_Left_shoulder;
    ModelRenderer Body_Right_shoulder;
    ModelRenderer Neck;
    ModelRenderer Head_base;
    ModelRenderer Head_slope;
    ModelRenderer Head_front;
    ModelRenderer Left_jaw;
    ModelRenderer Left_jaw_tip;
    ModelRenderer Right_jaw;
    ModelRenderer Right_jaw_tip;
    ModelRenderer Left_eye;
    ModelRenderer Right_eye;
    ModelRenderer Left_upper_arm;
    ModelRenderer Left_lower_arm;
    ModelRenderer Left_blade_base;
    ModelRenderer Left_blade_bottom;
    ModelRenderer Left_blade_top;
    ModelRenderer Right_upper_arm;
    ModelRenderer Right_lower_arm;
    ModelRenderer Right_blade_base;
    ModelRenderer Right_blade_bottom;
    ModelRenderer Right_blade_top;
    ModelRenderer Left_leg_base;
    ModelRenderer Left_leg_shin;
    ModelRenderer Left_outer_claws_base;
    ModelRenderer Left_outer_claws_front;
    ModelRenderer Left_outer_claws_rear;
    ModelRenderer Left_inner_claws_base;
    ModelRenderer Left_inner_claws_front;
    ModelRenderer Left_inner_claws_rear;
    ModelRenderer Right_leg_base;
    ModelRenderer Right_leg_shin;
    ModelRenderer Right_outer_claws_base;
    ModelRenderer Right_outer_claws_front;
    ModelRenderer Right_outer_claws_rear;
    ModelRenderer Right__inner_claws_base;
    ModelRenderer Right_inner_claws_front;
    ModelRenderer Right_inner_claws_rear;
    ModelRenderer Egg_case;
    ModelRenderer Egg_case_tip;
    ModelRenderer Egg_1;
    ModelRenderer Egg_2;
    ModelRenderer Egg_3;
    ModelRenderer Egg_4;
    ModelRenderer Egg_5;
    ModelRenderer L_Egg_1;
    ModelRenderer L_Egg_2;
    ModelRenderer L_Egg_3;
    ModelRenderer L_Egg_4;
    ModelRenderer L_Egg_5;
    ModelRenderer Body_mid_ridge;
  
  public ModelVesperQueen()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Body_base = new ModelRenderer(this, 72, 31);
      Body_base.addBox(-6F, -1F, -7F, 12, 17, 11);
      Body_base.setRotationPoint(0F, 2F, -2F);
      Body_base.setTextureSize(128, 128);
      Body_base.mirror = true;
      setRotation(Body_base, 0.8552113F, 0F, 0F);
      Body_mid = new ModelRenderer(this, 0, 18);
      Body_mid.addBox(-5F, -8.3F, -3.6F, 10, 10, 8);
      Body_mid.setRotationPoint(0F, 2F, -2F);
      Body_mid.setTextureSize(128, 128);
      Body_mid.mirror = true;
      setRotation(Body_mid, 0.2094395F, 0F, 0F);
      Body_Left_shoulder = new ModelRenderer(this, 0, 36);
      Body_Left_shoulder.addBox(-2F, -16.3F, -4.6F, 4, 10, 8);
      Body_Left_shoulder.setRotationPoint(0F, 2F, -2F);
      Body_Left_shoulder.setTextureSize(128, 128);
      Body_Left_shoulder.mirror = true;
      setRotation(Body_Left_shoulder, 0F, -0.0698132F, 0.5410521F);
      Body_Right_shoulder = new ModelRenderer(this, 0, 36);
      Body_Right_shoulder.addBox(-2F, -16.3F, -4.6F, 4, 10, 8);
      Body_Right_shoulder.setRotationPoint(0F, 2F, -2F);
      Body_Right_shoulder.setTextureSize(128, 128);
      Body_Right_shoulder.mirror = true;
      setRotation(Body_Right_shoulder, 0F, 0.0698132F, -0.5410521F);
      Neck = new ModelRenderer(this, 36, 0);
      Neck.addBox(-2.5F, -4F, -8F, 5, 4, 9);
      Neck.setRotationPoint(0F, -5F, -4F);
      Neck.setTextureSize(128, 128);
      Neck.mirror = true;
      setRotation(Neck, -0.1745329F, 0F, 0F);
      Head_base = new ModelRenderer(this, 36, 13);
      Head_base.addBox(-3.5F, -8F, -12F, 7, 6, 9);
      Head_base.setRotationPoint(0F, -5F, -4F);
      Head_base.setTextureSize(128, 128);
      Head_base.mirror = true;
      setRotation(Head_base, 0.2268928F, 0F, 0F);
      Head_slope = new ModelRenderer(this, 36, 28);
      Head_slope.addBox(-2.5F, -12F, -10F, 5, 6, 12);
      Head_slope.setRotationPoint(0F, -5F, -4F);
      Head_slope.setTextureSize(128, 128);
      Head_slope.mirror = true;
      setRotation(Head_slope, 0.6283185F, 0F, 0F);
      Head_front = new ModelRenderer(this, 68, 13);
      Head_front.addBox(-3F, -7F, -15F, 6, 5, 3);
      Head_front.setRotationPoint(0F, -5F, -4F);
      Head_front.setTextureSize(128, 128);
      Head_front.mirror = true;
      setRotation(Head_front, 0.2268928F, 0F, 0F);
      Left_jaw = new ModelRenderer(this, 68, 23);
      Left_jaw.addBox(-6F, -5F, -15F, 3, 2, 4);
      Left_jaw.setRotationPoint(0F, -5F, -4F);
      Left_jaw.setTextureSize(128, 128);
      Left_jaw.mirror = true;
      setRotation(Left_jaw, 0.3665191F, -0.5410521F, 0.1570796F);
      Left_jaw_tip = new ModelRenderer(this, 83, 23);
      Left_jaw_tip.addBox(1F, -2F, -18.46667F, 2, 1, 3);
      Left_jaw_tip.setRotationPoint(0F, -5F, -4F);
      Left_jaw_tip.setTextureSize(128, 128);
      Left_jaw_tip.mirror = true;
      setRotation(Left_jaw_tip, 0.1047198F, -0.0872665F, 0.1745329F);
      Right_jaw = new ModelRenderer(this, 68, 23);
      Right_jaw.addBox(3F, -5F, -15F, 3, 2, 4);
      Right_jaw.setRotationPoint(0F, -5F, -4F);
      Right_jaw.setTextureSize(128, 128);
      Right_jaw.mirror = true;
      setRotation(Right_jaw, 0.3665191F, 0.5410521F, -0.1570796F);
      Right_jaw_tip = new ModelRenderer(this, 83, 23);
      Right_jaw_tip.addBox(-3F, -2F, -18.46667F, 2, 1, 3);
      Right_jaw_tip.setRotationPoint(0F, -5F, -4F);
      Right_jaw_tip.setTextureSize(128, 128);
      Right_jaw_tip.mirror = true;
      setRotation(Right_jaw_tip, 0.1047198F, 0.0872665F, -0.1745329F);
      Left_eye = new ModelRenderer(this, 87, 13);
      Left_eye.addBox(3.5F, -8F, -12F, 2, 3, 5);
      Left_eye.setRotationPoint(0F, -5F, -4F);
      Left_eye.setTextureSize(128, 128);
      Left_eye.mirror = true;
      setRotation(Left_eye, 0.296706F, 0.122173F, 0F);
      Right_eye = new ModelRenderer(this, 87, 13);
      Right_eye.addBox(-5.5F, -8F, -12F, 2, 3, 5);
      Right_eye.setRotationPoint(0F, -5F, -4F);
      Right_eye.setTextureSize(128, 128);
      Right_eye.mirror = true;
      setRotation(Right_eye, 0.296706F, -0.122173F, 0F);
      Left_upper_arm = new ModelRenderer(this, 0, 94);
      Left_upper_arm.addBox(-2F, 0F, -2F, 4, 12, 4);
      Left_upper_arm.setRotationPoint(8F, -10F, -2F);
      Left_upper_arm.setTextureSize(128, 128);
      Left_upper_arm.mirror = true;
      setRotation(Left_upper_arm, -0.6283185F, -0.0698132F, -0.5061455F);
      Left_lower_arm = new ModelRenderer(this, 17, 94);
      Left_lower_arm.addBox(-1.5F, 8F, 5F, 3, 14, 4);
      Left_lower_arm.setRotationPoint(8F, -10F, -2F);
      Left_lower_arm.setTextureSize(128, 128);
      Left_lower_arm.mirror = true;
      setRotation(Left_lower_arm, -1.32645F, -0.0698132F, -0.5061455F);
      Left_blade_base = new ModelRenderer(this, 33, 94);
      Left_blade_base.addBox(-0.5F, 8F, -23F, 1, 11, 5);
      Left_blade_base.setRotationPoint(8F, -10F, -2F);
      Left_blade_base.setTextureSize(128, 128);
      Left_blade_base.mirror = true;
      setRotation(Left_blade_base, 0F, -0.0698132F, -0.5061455F);
      Left_blade_bottom = new ModelRenderer(this, 46, 94);
      Left_blade_bottom.addBox(-0.5F, 10F, -28F, 1, 19, 4);
      Left_blade_bottom.setRotationPoint(8F, -10F, -2F);
      Left_blade_bottom.setTextureSize(128, 128);
      Left_blade_bottom.mirror = true;
      setRotation(Left_blade_bottom, 0.3490659F, -0.0698132F, -0.5061455F);
      Left_blade_top = new ModelRenderer(this, 33, 111);
      Left_blade_top.addBox(-0.5F, 16.5F, -11.7F, 1, 5, 3);
      Left_blade_top.setRotationPoint(8F, -10F, -2F);
      Left_blade_top.setTextureSize(128, 128);
      Left_blade_top.mirror = true;
      setRotation(Left_blade_top, -0.7330383F, -0.0698132F, -0.5061455F);
      Right_upper_arm = new ModelRenderer(this, 0, 94);
      Right_upper_arm.addBox(-2F, 0F, -2F, 4, 12, 4);
      Right_upper_arm.setRotationPoint(-8F, -10F, -2F);
      Right_upper_arm.setTextureSize(128, 128);
      Right_upper_arm.mirror = true;
      setRotation(Right_upper_arm, -0.6283185F, 0.0698132F, 0.5061455F);
      Right_lower_arm = new ModelRenderer(this, 17, 94);
      Right_lower_arm.addBox(-1.5F, 8F, 5F, 3, 14, 4);
      Right_lower_arm.setRotationPoint(-8F, -10F, -2F);
      Right_lower_arm.setTextureSize(128, 128);
      Right_lower_arm.mirror = true;
      setRotation(Right_lower_arm, -1.32645F, 0.0698132F, 0.5061455F);
      Right_blade_base = new ModelRenderer(this, 33, 94);
      Right_blade_base.addBox(-0.5F, 8F, -23F, 1, 11, 5);
      Right_blade_base.setRotationPoint(-8F, -10F, -2F);
      Right_blade_base.setTextureSize(128, 128);
      Right_blade_base.mirror = true;
      setRotation(Right_blade_base, 0F, 0.0698132F, 0.5061455F);
      Right_blade_bottom = new ModelRenderer(this, 46, 94);
      Right_blade_bottom.addBox(-0.5F, 10F, -28F, 1, 19, 4);
      Right_blade_bottom.setRotationPoint(-8F, -10F, -2F);
      Right_blade_bottom.setTextureSize(128, 128);
      Right_blade_bottom.mirror = true;
      setRotation(Right_blade_bottom, 0.3490659F, 0.0698132F, 0.5061455F);
      Right_blade_top = new ModelRenderer(this, 33, 111);
      Right_blade_top.addBox(-0.5F, 16.5F, -11.7F, 1, 5, 3);
      Right_blade_top.setRotationPoint(-8F, -10F, -2F);
      Right_blade_top.setTextureSize(128, 128);
      Right_blade_top.mirror = true;
      setRotation(Right_blade_top, -0.7330383F, 0.0698132F, 0.5061455F);
      Left_leg_base = new ModelRenderer(this, 32, 67);
      Left_leg_base.addBox(0F, -2F, -3F, 5, 11, 6);
      Left_leg_base.setRotationPoint(6F, 7F, 3F);
      Left_leg_base.setTextureSize(128, 128);
      Left_leg_base.mirror = true;
      setRotation(Left_leg_base, -0.5061455F, 0F, -0.3141593F);
      Left_leg_shin = new ModelRenderer(this, 56, 67);
      Left_leg_shin.addBox(3F, 2F, -9F, 3, 12, 4);
      Left_leg_shin.setRotationPoint(6F, 7F, 3F);
      Left_leg_shin.setTextureSize(128, 128);
      Left_leg_shin.mirror = true;
      setRotation(Left_leg_shin, 0.5061455F, 0F, 0F);
      Left_outer_claws_base = new ModelRenderer(this, 57, 83);
      Left_outer_claws_base.addBox(5F, 13F, -8F, 3, 4, 10);
      Left_outer_claws_base.setRotationPoint(6F, 7F, 3F);
      Left_outer_claws_base.setTextureSize(128, 128);
      Left_outer_claws_base.mirror = true;
      setRotation(Left_outer_claws_base, 0F, 0F, 0F);
      Left_outer_claws_front = new ModelRenderer(this, 57, 98);
      Left_outer_claws_front.addBox(5.5F, 12F, -17F, 2, 3, 9);
      Left_outer_claws_front.setRotationPoint(6F, 7F, 3F);
      Left_outer_claws_front.setTextureSize(128, 128);
      Left_outer_claws_front.mirror = true;
      setRotation(Left_outer_claws_front, 0.1396263F, 0F, 0F);
      Left_outer_claws_rear = new ModelRenderer(this, 57, 112);
      Left_outer_claws_rear.addBox(5.5F, 14F, 2F, 2, 3, 4);
      Left_outer_claws_rear.setRotationPoint(6F, 7F, 3F);
      Left_outer_claws_rear.setTextureSize(128, 128);
      Left_outer_claws_rear.mirror = true;
      setRotation(Left_outer_claws_rear, 0F, 0F, 0F);
      Left_inner_claws_base = new ModelRenderer(this, 57, 83);
      Left_inner_claws_base.addBox(1F, 13F, -8F, 3, 4, 10);
      Left_inner_claws_base.setRotationPoint(6F, 7F, 3F);
      Left_inner_claws_base.setTextureSize(128, 128);
      Left_inner_claws_base.mirror = true;
      setRotation(Left_inner_claws_base, 0F, 0F, 0F);
      Left_inner_claws_front = new ModelRenderer(this, 57, 98);
      Left_inner_claws_front.addBox(1.5F, 12F, -17F, 2, 3, 9);
      Left_inner_claws_front.setRotationPoint(6F, 7F, 3F);
      Left_inner_claws_front.setTextureSize(128, 128);
      Left_inner_claws_front.mirror = true;
      setRotation(Left_inner_claws_front, 0.1396263F, 0F, 0F);
      Left_inner_claws_rear = new ModelRenderer(this, 57, 112);
      Left_inner_claws_rear.addBox(1.5F, 14F, 2F, 2, 3, 4);
      Left_inner_claws_rear.setRotationPoint(6F, 7F, 3F);
      Left_inner_claws_rear.setTextureSize(128, 128);
      Left_inner_claws_rear.mirror = true;
      setRotation(Left_inner_claws_rear, 0F, 0F, 0F);
      Right_leg_base = new ModelRenderer(this, 32, 67);
      Right_leg_base.addBox(-5F, -2F, -3F, 5, 11, 6);
      Right_leg_base.setRotationPoint(-6F, 7F, 3F);
      Right_leg_base.setTextureSize(128, 128);
      Right_leg_base.mirror = true;
      setRotation(Right_leg_base, -0.5061455F, 0F, 0.3141593F);
      Right_leg_shin = new ModelRenderer(this, 56, 67);
      Right_leg_shin.addBox(-6F, 2F, -9F, 3, 12, 4);
      Right_leg_shin.setRotationPoint(-6F, 7F, 3F);
      Right_leg_shin.setTextureSize(128, 128);
      Right_leg_shin.mirror = true;
      setRotation(Right_leg_shin, 0.5061455F, 0F, 0F);
      Right_outer_claws_base = new ModelRenderer(this, 57, 83);
      Right_outer_claws_base.addBox(-8F, 13F, -8F, 3, 4, 10);
      Right_outer_claws_base.setRotationPoint(-6F, 7F, 3F);
      Right_outer_claws_base.setTextureSize(128, 128);
      Right_outer_claws_base.mirror = true;
      setRotation(Right_outer_claws_base, 0F, 0F, 0F);
      Right_outer_claws_front = new ModelRenderer(this, 57, 98);
      Right_outer_claws_front.addBox(-7.5F, 12F, -17F, 2, 3, 9);
      Right_outer_claws_front.setRotationPoint(-6F, 7F, 3F);
      Right_outer_claws_front.setTextureSize(128, 128);
      Right_outer_claws_front.mirror = true;
      setRotation(Right_outer_claws_front, 0.1396263F, 0F, 0F);
      Right_outer_claws_rear = new ModelRenderer(this, 57, 112);
      Right_outer_claws_rear.addBox(-7.5F, 14F, 2F, 2, 3, 4);
      Right_outer_claws_rear.setRotationPoint(-6F, 7F, 3F);
      Right_outer_claws_rear.setTextureSize(128, 128);
      Right_outer_claws_rear.mirror = true;
      setRotation(Right_outer_claws_rear, 0F, 0F, 0F);
      Right__inner_claws_base = new ModelRenderer(this, 57, 83);
      Right__inner_claws_base.addBox(-4F, 13F, -8F, 3, 4, 10);
      Right__inner_claws_base.setRotationPoint(-6F, 7F, 3F);
      Right__inner_claws_base.setTextureSize(128, 128);
      Right__inner_claws_base.mirror = true;
      setRotation(Right__inner_claws_base, 0F, 0F, 0F);
      Right_inner_claws_front = new ModelRenderer(this, 57, 98);
      Right_inner_claws_front.addBox(-3.5F, 12F, -17F, 2, 3, 9);
      Right_inner_claws_front.setRotationPoint(-6F, 7F, 3F);
      Right_inner_claws_front.setTextureSize(128, 128);
      Right_inner_claws_front.mirror = true;
      setRotation(Right_inner_claws_front, 0.1396263F, 0F, 0F);
      Right_inner_claws_rear = new ModelRenderer(this, 57, 112);
      Right_inner_claws_rear.addBox(-3.5F, 14F, 2F, 2, 3, 4);
      Right_inner_claws_rear.setRotationPoint(-6F, 7F, 3F);
      Right_inner_claws_rear.setTextureSize(128, 128);
      Right_inner_claws_rear.mirror = true;
      setRotation(Right_inner_claws_rear, 0F, 0F, 0F);
      Egg_case = new ModelRenderer(this, 102, 0);
      Egg_case.addBox(-3.5F, -1F, -6F, 7, 12, 6);
      Egg_case.setRotationPoint(0F, 7F, 8F);
      Egg_case.setTextureSize(128, 128);
      Egg_case.mirror = true;
      setRotation(Egg_case, 1.117011F, 0F, 0F);
      Egg_case_tip = new ModelRenderer(this, 84, 0);
      Egg_case_tip.addBox(-2.5F, 9F, -5F, 5, 3, 4);
      Egg_case_tip.setRotationPoint(0F, 7F, 8F);
      Egg_case_tip.setTextureSize(128, 128);
      Egg_case_tip.mirror = true;
      setRotation(Egg_case_tip, 1.117011F, 0F, 0F);
      Egg_1 = new ModelRenderer(this, 102, 19);
      Egg_1.addBox(-4.5F, 1F, 0F, 3, 3, 3);
      Egg_1.setRotationPoint(0F, 7F, 8F);
      Egg_1.setTextureSize(128, 128);
      Egg_1.mirror = true;
      setRotation(Egg_1, 0.837758F, 0F, 0F);
      Egg_2 = new ModelRenderer(this, 102, 19);
      Egg_2.addBox(-4.5F, 4.5F, 0F, 3, 3, 3);
      Egg_2.setRotationPoint(0F, 7F, 8F);
      Egg_2.setTextureSize(128, 128);
      Egg_2.mirror = true;
      setRotation(Egg_2, 0.837758F, 0F, 0F);
      Egg_3 = new ModelRenderer(this, 102, 19);
      Egg_3.addBox(-4.5F, 8.3F, -2.3F, 3, 3, 3);
      Egg_3.setRotationPoint(0F, 7F, 8F);
      Egg_3.setTextureSize(128, 128);
      Egg_3.mirror = true;
      setRotation(Egg_3, 1.117011F, 0F, 0F);
      Egg_4 = new ModelRenderer(this, 102, 19);
      Egg_4.addBox(-4.5F, 7.8F, -7.3F, 3, 3, 3);
      Egg_4.setRotationPoint(0F, 7F, 8F);
      Egg_4.setTextureSize(128, 128);
      Egg_4.mirror = true;
      setRotation(Egg_4, 1.117011F, 0F, 0F);
      Egg_5 = new ModelRenderer(this, 102, 19);
      Egg_5.addBox(-4.5F, 4.3F, -7.3F, 3, 3, 3);
      Egg_5.setRotationPoint(0F, 7F, 8F);
      Egg_5.setTextureSize(128, 128);
      Egg_5.mirror = true;
      setRotation(Egg_5, 1.117011F, 0F, 0F);
      L_Egg_1 = new ModelRenderer(this, 102, 19);
      L_Egg_1.addBox(1.5F, 1F, 0F, 3, 3, 3);
      L_Egg_1.setRotationPoint(0F, 7F, 8F);
      L_Egg_1.setTextureSize(128, 128);
      L_Egg_1.mirror = true;
      setRotation(L_Egg_1, 0.837758F, 0F, 0F);
      L_Egg_2 = new ModelRenderer(this, 102, 19);
      L_Egg_2.addBox(1.5F, 4.5F, 0F, 3, 3, 3);
      L_Egg_2.setRotationPoint(0F, 7F, 8F);
      L_Egg_2.setTextureSize(128, 128);
      L_Egg_2.mirror = true;
      setRotation(L_Egg_2, 0.837758F, 0F, 0F);
      L_Egg_3 = new ModelRenderer(this, 102, 19);
      L_Egg_3.addBox(1.5F, 8.3F, -2.3F, 3, 3, 3);
      L_Egg_3.setRotationPoint(0F, 7F, 8F);
      L_Egg_3.setTextureSize(128, 128);
      L_Egg_3.mirror = true;
      setRotation(L_Egg_3, 1.117011F, 0F, 0F);
      L_Egg_4 = new ModelRenderer(this, 102, 19);
      L_Egg_4.addBox(1.5F, 7.8F, -7.3F, 3, 3, 3);
      L_Egg_4.setRotationPoint(0F, 7F, 8F);
      L_Egg_4.setTextureSize(128, 128);
      L_Egg_4.mirror = true;
      setRotation(L_Egg_4, 1.117011F, 0F, 0F);
      L_Egg_5 = new ModelRenderer(this, 102, 19);
      L_Egg_5.addBox(1.5F, 4.3F, -7.3F, 3, 3, 3);
      L_Egg_5.setRotationPoint(0F, 7F, 8F);
      L_Egg_5.setTextureSize(128, 128);
      L_Egg_5.mirror = true;
      setRotation(L_Egg_5, 1.117011F, 0F, 0F);
      Body_mid_ridge = new ModelRenderer(this, 3, 0);
      Body_mid_ridge.addBox(-4F, -5.3F, -5.6F, 8, 10, 6);
      Body_mid_ridge.setRotationPoint(0F, 2F, -2F);
      Body_mid_ridge.setTextureSize(128, 128);
      Body_mid_ridge.mirror = true;
      setRotation(Body_mid_ridge, -0.0349066F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body_base.render(f5);
    Body_mid.render(f5);
    Body_Left_shoulder.render(f5);
    Body_Right_shoulder.render(f5);
    Neck.render(f5);
    Head_base.render(f5);
    Head_slope.render(f5);
    Head_front.render(f5);
    Left_jaw.render(f5);
    Left_jaw_tip.render(f5);
    Right_jaw.render(f5);
    Right_jaw_tip.render(f5);
    Left_eye.render(f5);
    Right_eye.render(f5);
    Left_upper_arm.render(f5);
    Left_lower_arm.render(f5);
    Left_blade_base.render(f5);
    Left_blade_bottom.render(f5);
    Left_blade_top.render(f5);
    Right_upper_arm.render(f5);
    Right_lower_arm.render(f5);
    Right_blade_base.render(f5);
    Right_blade_bottom.render(f5);
    Right_blade_top.render(f5);
    Left_leg_base.render(f5);
    Left_leg_shin.render(f5);
    Left_outer_claws_base.render(f5);
    Left_outer_claws_front.render(f5);
    Left_outer_claws_rear.render(f5);
    Left_inner_claws_base.render(f5);
    Left_inner_claws_front.render(f5);
    Left_inner_claws_rear.render(f5);
    Right_leg_base.render(f5);
    Right_leg_shin.render(f5);
    Right_outer_claws_base.render(f5);
    Right_outer_claws_front.render(f5);
    Right_outer_claws_rear.render(f5);
    Right__inner_claws_base.render(f5);
    Right_inner_claws_front.render(f5);
    Right_inner_claws_rear.render(f5);
    Egg_case.render(f5);
    Egg_case_tip.render(f5);
    Egg_1.render(f5);
    Egg_2.render(f5);
    Egg_3.render(f5);
    Egg_4.render(f5);
    Egg_5.render(f5);
    L_Egg_1.render(f5);
    L_Egg_2.render(f5);
    L_Egg_3.render(f5);
    L_Egg_4.render(f5);
    L_Egg_5.render(f5);
    Body_mid_ridge.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  
  
}
